import type { DetectionPattern, DetectionType, HardcodedString } from './types/localization'

/**
 * Advanced pattern matcher for detecting hardcoded strings in various contexts
 */
export class PatternMatcher {
  private patterns: Map<DetectionType, DetectionPattern[]>

  constructor() {
    this.patterns = new Map()
    this.initializePatterns()
  }

  /**
   * Find matches for a specific detection type
   */
  findMatches(content: string, type: DetectionType): HardcodedString[] {
    const patterns = this.patterns.get(type) || []
    const matches: HardcodedString[] = []

    for (const pattern of patterns) {
      const regexMatches = content.matchAll(pattern.pattern)
      
      for (const match of regexMatches) {
        const text = pattern.extractor(match)
        if (!text || this.shouldExcludeString(text, content)) {
          continue
        }

        const line = this.getLineNumber(content, match.index || 0)
        const column = this.getColumnNumber(content, match.index || 0)

        matches.push({
          text: text.trim(),
          type,
          filePath: '', // Will be set by caller
          line,
          column,
          suggestedKey: '', // Will be generated by caller
          context: this.getContextAround(content, match.index || 0)
        })
      }
    }

    return matches
  }

  /**
   * Find matches with enhanced context information
   */
  findMatchesWithContext(content: string, type: DetectionType, contextSize = 100): HardcodedString[] {
    const matches = this.findMatches(content, type)
    
    return matches.map(match => ({
      ...match,
      context: this.getContextAround(content, this.findStringIndex(content, match.text), contextSize)
    }))
  }

  /**
   * Get all available detection types
   */
  getAvailableTypes(): DetectionType[] {
    return Array.from(this.patterns.keys())
  }

  /**
   * Add custom pattern for detection
   */
  addCustomPattern(type: DetectionType, pattern: DetectionPattern): void {
    if (!this.patterns.has(type)) {
      this.patterns.set(type, [])
    }
    this.patterns.get(type)!.push(pattern)
  }

  private initializePatterns(): void {
    // JSX Text Content
    this.patterns.set('jsx_text', [
      {
        pattern: />([^<>{]+)</g,
        type: 'jsx_text',
        extractor: (match) => {
          const text = match[1]?.trim()
          // Exclude JSX expressions and empty text
          if (!text || text.includes('{') || text.includes('}')) return null
          // Exclude very short text
          if (text.length < 3) return null
          return text
        },
        contextExtractor: (match, content) => this.getContextAround(content, match.index || 0)
      }
    ])

    // Button Labels
    this.patterns.set('button_label', [
      {
        pattern: /<Button[^>]*>\s*(?:<[^>]*>)?\s*([^<{]+?)(?:\s*<[^>]*>)?\s*<\/Button>/g,
        type: 'button_label',
        extractor: (match) => match[1]?.trim() || null
      },
      {
        pattern: /<Button[^>]*>\s*([^<{]+)\s*<\/Button>/g,
        type: 'button_label',
        extractor: (match) => match[1]?.trim() || null
      }
    ])

    // Tooltip Content
    this.patterns.set('tooltip', [
      {
        pattern: /<TooltipContent[^>]*>[\s\S]*?<p[^>]*>\s*([^<]+)\s*<\/p>[\s\S]*?<\/TooltipContent>/g,
        type: 'tooltip',
        extractor: (match) => match[1]?.trim() || null
      },
      {
        pattern: /<TooltipContent[^>]*>\s*([^<]+)\s*<\/TooltipContent>/g,
        type: 'tooltip',
        extractor: (match) => match[1]?.trim() || null
      }
    ])

    // Form Placeholders
    this.patterns.set('placeholder', [
      {
        pattern: /placeholder=["']([^"']+)["']/g,
        type: 'placeholder',
        extractor: (match) => match[1] || null
      }
    ])

    // Form Labels
    this.patterns.set('form_label', [
      {
        pattern: /<Label[^>]*>\s*([^<]+)\s*<\/Label>/g,
        type: 'form_label',
        extractor: (match) => match[1]?.trim() || null
      },
      {
        pattern: /<label[^>]*>\s*([^<]+)\s*<\/label>/g,
        type: 'form_label',
        extractor: (match) => match[1]?.trim() || null
      }
    ])

    // Error Messages
    this.patterns.set('error_message', [
      {
        pattern: /throw new Error\(["']([^"']+)["']\)/g,
        type: 'error_message',
        extractor: (match) => match[1] || null
      }
    ])

    // Validation Messages
    this.patterns.set('validation_message', [
      {
        pattern: /:\s*["']([^"']+)["']/g,
        type: 'validation_message',
        extractor: (match) => {
          const text = match[1]
          // Only include if it looks like a validation message
          if (text && (text.includes('required') || text.includes('invalid') || text.includes('enter'))) {
            return text
          }
          return null
        }
      }
    ])

    // Chart Labels
    this.patterns.set('chart_label', [
      {
        pattern: /(?:title|label|xAxisLabel|yAxisLabel):\s*["']([^"']+)["']/g,
        type: 'chart_label',
        extractor: (match) => match[1] || null
      }
    ])

    // Alert Messages
    this.patterns.set('alert_message', [
      {
        pattern: /<Alert[^>]*>[\s\S]*?([^<]+)[\s\S]*?<\/Alert>/g,
        type: 'alert_message',
        extractor: (match) => match[1]?.trim() || null
      }
    ])

    // Modal Content
    this.patterns.set('modal_content', [
      {
        pattern: /<Modal[^>]*>[\s\S]*?<h[1-6][^>]*>\s*([^<]+)\s*<\/h[1-6]>[\s\S]*?<\/Modal>/g,
        type: 'modal_content',
        extractor: (match) => match[1]?.trim() || null
      }
    ])
  }

  private shouldExcludeString(text: string, content: string): boolean {
    // Exclude very short strings
    if (text.length < 3) return true

    // Exclude strings that are already using translation functions
    const translationPattern = /[{]\s*(?:t|safeT)\s*\(/
    if (translationPattern.test(text)) return true

    // Exclude technical strings
    const technicalPatterns = [
      /^[A-Z_]+$/, // ALL_CAPS constants
      /^[a-z-]+$/, // CSS class names (single words with dashes)
      /^\d+$/, // Pure numbers
      /^[./]/, // File paths
      /console\.|import |export |from |require\(/, // Code keywords
      /^(true|false|null|undefined)$/, // JavaScript literals
      /^[a-zA-Z]+\([^)]*\)$/, // Function calls
    ]

    if (technicalPatterns.some(pattern => pattern.test(text.trim()))) return true

    // Exclude if the text is part of a translation call
    const textIndex = content.indexOf(text)
    if (textIndex !== -1) {
      const beforeText = content.substring(Math.max(0, textIndex - 50), textIndex)
      if (beforeText.includes('t(') || beforeText.includes('safeT(')) return true

      // Check if text contains JSX expressions
      if (text.includes('{') || text.includes('}')) return true
    }

    return false
  }

  private getLineNumber(content: string, index: number): number {
    return content.substring(0, index).split('\n').length
  }

  private getColumnNumber(content: string, index: number): number {
    const lines = content.substring(0, index).split('\n')
    return lines[lines.length - 1].length + 1
  }

  private getContextAround(content: string, index: number, contextSize = 50): string {
    const start = Math.max(0, index - contextSize)
    const end = Math.min(content.length, index + contextSize)
    return content.substring(start, end).trim()
  }

  private findStringIndex(content: string, text: string): number {
    return content.indexOf(text)
  }
}
