import Link from 'next/link'
import { LegalFooter } from '@/components/legal-footer'
export const metadata = { title: 'Methodik & Modelle | FireHODL' }
export default function Methodik() {
  return <main className="container mx-auto max-w-3xl px-6 py-10 space-y-7">
    <Link className="text-sm text-muted-foreground underline" href="/">← Zum Simulator</Link>
    <h1 className="text-3xl font-bold">Methodik & Modelle</h1>
    <p>FireHODL untersucht Bitcoin-Szenarien. Ein Szenario beschreibt Annahmen und deren Folgen, keine Vorhersage und keine Empfehlung für eine Anlage oder einen Kreditanbieter. Beträge werden in USD vor Steuern gezeigt.</p>
    <h2 className="text-xl font-semibold">Die ursprüngliche Oberfläche als Basis</h2>
    <p>Parameter definieren Bestand und Kredit. Die Projektion legt den gemeinsamen Kursverlauf fest. Strategie und Ergebnisse beschreiben die Verwendung des Bestands. Die ursprüngliche Oberfläche verwendet einen gemeinsamen Tagesrechner. Ergebnisse, Vergleich und CSV lesen dieselben Kurse und Zahlungsströme.</p>
    <h2 className="text-xl font-semibold">Eigene Jahresszenarien</h2>
    <p>Im manuellen Modell gibst du für jedes Jahr eine positive oder negative Kursänderung vor. Innerhalb des Jahres wird geometrisch auf Monatsstände und dazwischen auf Tagesstände verteilt. Vorhandene Presets enthalten Auf- und Abschwungjahre. Sie sind Annahmen, keine historischen Daten. Zwischen den Monatsständen enthält dieses Modell keine zusätzlichen Tagescrashs.</p>
    <h2 className="text-xl font-semibold">Historische Zykluswiederholung</h2>
    <p>Du kannst die letzten vier verfügbaren Datenjahre oder die abgeschlossenen Halving-Zeiträume 2016–2020 und 2020–2024 auswählen. Die prozentualen Tagesbewegungen werden auf deinen Startkurs übertragen. Der Einstieg lässt sich um Monate innerhalb der Vorlage verschieben. Nach deren Ende beginnt dieselbe Abfolge erneut. Fehlende Tageskurse führen zu einer Fehlermeldung, nicht zu einem erfundenen Ersatzverlauf.</p>
    <p>Die Dämpfung betrifft nur den positiven Gewinnanteil oberhalb der eingestellten Tagesschwelle; mindestens zehn Prozent des ursprünglichen Tagesgewinns bleiben erhalten. Verlusttage bleiben unverändert. Die Tages-OHLC werden relativ zum historischen Vortag übernommen und an den veränderten Schlusskurs angepasst. Das ist ein konstruiertes Szenario, kein beobachteter zukünftiger Kurs.</p>
    <p>Bitcoin halbiert seine Blocksubvention alle 210.000 Blöcke, ungefähr alle vier Jahre. Daraus folgt kein fest vorgeschriebener Kurszyklus. Länge und Stärke von Rallys, Bärenmärkten und Erholungen können sich ändern. Deshalb sollten verschiedene Vorlagen und Einstiegsphasen geprüft werden. <a className="underline" href="https://developer.bitcoin.org/reference/block_chain.html">Bitcoin-Protokollreferenz</a></p>
    <h2 className="text-xl font-semibold">Power Law</h2>
    <p>Power Law ist eine langfristige Trendannahme über die Zeit seit dem Genesis-Block. Der erste Punkt ist dein Startkurs; ab dem ersten Monatsende gelten die absoluten Modellkurse. Dieser Übergang ist eine Szenarioannahme und kann bereits im ersten Monat eine große Kursänderung erzeugen. Die vorhandene optionale historische Volatilitätsüberlagerung bleibt verfügbar. Fit, Support und Resistance sind Modelllinien, keine garantierten Kursgrenzen und keine statistischen Konfidenzintervalle.</p>
    <h2 className="text-xl font-semibold">Kennzahlen zum Kursverlauf</h2>
    <p>Die Projektion zeigt Endkurs, gesamte Kursänderung, geometrisches Wachstum pro Jahr (CAGR), stärkstes abgeschlossenes Simulationsjahr und den größten Rückgang von einem zuvor erreichten Hoch. Diese Kennzahlen beziehen sich auf die Kursstände des Modells. Bei glatten Monatsprojektionen fehlen Bewegungen innerhalb des Monats. Es wird keine Eintritts- oder Liquidationswahrscheinlichkeit geschätzt.</p>
    <h2 className="text-xl font-semibold">Käufe und faire Vergleiche</h2>
    <p>Alle Strategien erhalten dieselben Anfangsbestände, Einzahlungen, Entnahmeziele und denselben Kursverlauf. Die erste Sparrate fließt nach einem vollen Kalendermonat zum Tagesschluss. Bei ATH-Regeln wird der vorherige Schlusskurs mit dem bis dahin bekannten Tageshoch verglichen; Ausführung ist zur nächsten Eröffnung. Der gleitende Durchschnitt verwendet nur abgeschlossene Tage. Fehlen unmittelbar vorausgehende historische Kurse, beginnt seine Aufbauphase am Simulationsstart. Uninvestiertes Geld bleibt als Cash erhalten, ohne angenommene Verzinsung.</p>
    <h2 className="text-xl font-semibold">Kredite, Sicherheiten und Tagestiefs</h2>
    <p>Kreditgebühren werden mitfinanziert. Bei jährlichen Gebühren wird die feste Laufzeit anteilig berücksichtigt. Zinsen laufen täglich einfach auf die Kredithauptsumme auf; bei Refinanzierung werden offene Zinsen und Gebühren kapitalisiert. Das Kreditlimit begrenzt die neue Gesamtschuld einschließlich Gebühren, nicht nur die Auszahlung.</p>
    <p>Nur die tatsächlich verpfändeten BTC bestimmen den LTV. Freie BTC bleiben separat. Die Liquidationsschwelle ist Schuld geteilt durch verpfändete BTC und Liquidations-LTV. Sie verändert sich mit Zinsen, neuen Krediten und Sicherheiten. Bei aktivierter Nachbesicherung werden freie BTC unmittelbar am Tagestief zur Sicherheit hinzugefügt, wenn das maximale Kredit-LTV überschritten wird. Diese ideale Ausführung berücksichtigt keine Verzögerungen.</p>
    <p>Die Liquidationsprüfung nutzt das Tagestief vor den Zahlungsströmen zum Tagesschluss. Liquidiert werden die verpfändeten BTC zum Tagestief abzüglich Liquidationsgebühr; freie BTC bleiben bestehen. Vorhandenes Cash wird zur Schuldentilgung genutzt. Restschuld bleibt offen, weitere Kreditaufnahmen stoppen. Bei Fälligkeit wird nur refinanziert, wenn die eingestellten Grenzen reichen; andernfalls werden BTC zur Rückzahlung verkauft.</p>
    <p>Der zusätzliche Flashcrash verändert das Tagestief am gewählten Monatsstichtag, aber nicht den Schlusskurs. Deshalb kann er eine Liquidation verursachen, ohne die Schlusskurskurve zu verändern. Die Kurve „Schwelle bei Einsatz aller BTC“ ist ein hypothetischer Vergleich zur tatsächlich verpfändeten Position.</p>
    <h2 className="text-xl font-semibold">Ergebnis und Grenzen</h2>
    <p>Nettovermögen ist BTC-Wert plus Cash minus Schulden. Gewinn berücksichtigt zusätzlich ausgezahlte Entnahmen und zieht Startvermögen sowie Einzahlungen ab. Die zeitgewichtete Rendite bereinigt externe Zahlungsströme; ihr Höchststand-Rückgang misst den Verlust im bereinigten Renditeverlauf. Gebühren und Zinsen sind bereits berücksichtigt. Eine nicht finanzierbare Entnahme wird als Lücke ausgewiesen.</p>
    <p>Es gibt keine Aussage über eine allgemein beste Strategie oder eine Liquidationswahrscheinlichkeit. Nicht modelliert sind Steuern, Handelsliquidität, Slippage, Ausfall eines Anbieters, variable Zinssätze und Reaktionszeiten. Bei Monatsmodellen fehlen zusätzliche echte Tagesbewegungen. Plattform-Presets sind editierbare Annahmen und keine Zusage aktueller Produktkonditionen. Gespeicherte Szenarien bleiben lokal in diesem Browser und starten beim Laden mit den gespeicherten Annahmen am heutigen Datum.</p>
    <LegalFooter className="border-t pt-6 flex flex-wrap gap-4 text-xs text-muted-foreground" />
  </main>
}
